sudo: required
language: node_js
before_install: 
  - npm install -g grunt-cli
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
install:
  - npm install
  - jspm install
  - gem install sass
  - gem install sass-globbing -v 1.1.0
  - gem install --pre sass-css-importer
script:
  - grunt build
  - jspm bundle-sfx src/js/main build/js/jefftherobot.bundle.js --skip-source-maps --minify
after_success:
  - sudo apt-get -y install sshpass
  - sshpass -p $DEPLOY_PASS scp -o stricthostkeychecking=no -r build $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
