language: node_js
before_install: 
  - npm install -g grunt-cli
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
install:
  - npm install
  - jspm install
  - gem install sass
  - gem install sass-globbing -v 1.1.0
  - gem install --pre sass-css-importer
script:
  - grunt build
  - jspm bundle-sfx src/js/main build/js/jefftherobot.bundle.js --skip-source-maps --minify
after_success:
  - "find build -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://jefftherobot.com/usr/local/www/data/jefftherobot.com/htdocs/{} \;"
